# Interactive Cosmograph visualization of SSNs for MGnify proteins

TODO: talk bla bla, mgnfiy logo

## Setting up the environment

### Install required packages

In [1]:
%pip install duckdb cosmograph pyarrow ipywidgets

Requirement already satisfied: duckdb in /home/szabolcs/miniconda3/lib/python3.13/site-packages (1.5.5)
Requirement already satisfied: cosmograph in /home/szabolcs/miniconda3/lib/python3.13/site-packages (0.5.3)
Requirement already satisfied: pyarrow in /home/szabolcs/miniconda3/lib/python3.13/site-packages (25.0.0)
Requirement already satisfied: ipywidgets in /home/szabolcs/miniconda3/lib/python3.13/site-packages (8.1.8)
Requirement already satisfied: anywidget in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (0.11.0)
Requirement already satisfied: dol>=0.3.30 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (0.3.56)
Requirement already satisfied: i2>=0.1.58 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (0.1.64)
Requirement already satisfied: joblib in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (1.5.3)
Requirement already satisfied: ju>=0.1.31 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (0.1.31)
Requirement already satisfied: numpy in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (2.5.1)
Requirement already satisfied: pandas in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (3.0.3)
Requirement already satisfied: tabled>=0.1.26 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (0.1.29)
Requirement already satisfied: traitlets in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from cosmograph) (5.15.1)
Requirement already satisfied: comm>=0.1.3 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipywidgets) (9.15.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: decorator>=5.1.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: psutil>=7 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: importlib-resources in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ju>=0.1.31->cosmograph) (7.1.0)
Requirement already satisfied: pydantic in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ju>=0.1.31->cosmograph) (2.13.2)
Requirement already satisfied: glom in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ju>=0.1.31->cosmograph) (25.12.0)
Requirement already satisfied: datamodel-code-generator in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ju>=0.1.31->cosmograph) (0.69.0)
Requirement already satisfied: requests in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from ju>=0.1.31->cosmograph) (2.33.1)
Requirement already satisfied: ptyprocess>=0.5 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.2)
Requirement already satisfied: pure_eval in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: charset-normalizer in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from tabled>=0.1.26->cosmograph) (3.4.4)
Requirement already satisfied: lxml in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from tabled>=0.1.26->cosmograph) (6.1.1)
Requirement already satisfied: psygnal>=0.8.1 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from anywidget->cosmograph) (0.15.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from anywidget->cosmograph) (4.15.0)
Requirement already satisfied: argcomplete<4,>=2.10.1 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from datamodel-code-generator->ju>=0.1.31->cosmograph) (3.7.0)
Requirement already satisfied: black>=19.10b0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from datamodel-code-generator->ju>=0.1.31->cosmograph) (26.5.1)
Requirement already satisfied: genson<2,>=1.2.1 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from datamodel-code-generator->ju>=0.1.31->cosmograph) (1.4.0)
Requirement already satisfied: inflect<8,>=4.1 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from datamodel-code-generator->ju>=0.1.31->cosmograph) (7.5.0)
Requirement already satisfied: isort<9,>=4.3.21 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from datamodel-code-generator->ju>=0.1.31->cosmograph) (8.0.1)
Requirement already satisfied: jinja2<4,>=2.10.1 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from datamodel-code-generator->ju>=0.1.31->cosmograph) (3.1.6)
Requirement already satisfied: pyyaml>=6.0.1 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from datamodel-code-generator->ju>=0.1.31->cosmograph) (6.0.3)
Requirement already satisfied: more_itertools>=8.5.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from inflect<8,>=4.1->datamodel-code-generator->ju>=0.1.31->cosmograph) (11.0.2)
Requirement already satisfied: typeguard>=4.0.1 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from inflect<8,>=4.1->datamodel-code-generator->ju>=0.1.31->cosmograph) (4.5.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from jinja2<4,>=2.10.1->datamodel-code-generator->ju>=0.1.31->cosmograph) (3.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from pydantic->ju>=0.1.31->cosmograph) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.2 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from pydantic->ju>=0.1.31->cosmograph) (2.46.2)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from pydantic->ju>=0.1.31->cosmograph) (0.4.2)
Requirement already satisfied: click>=8.0.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from black>=19.10b0->datamodel-code-generator->ju>=0.1.31->cosmograph) (8.2.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from black>=19.10b0->datamodel-code-generator->ju>=0.1.31->cosmograph) (1.1.0)
Requirement already satisfied: packaging>=22.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from black>=19.10b0->datamodel-code-generator->ju>=0.1.31->cosmograph) (26.0)
Requirement already satisfied: pathspec>=1.0.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from black>=19.10b0->datamodel-code-generator->ju>=0.1.31->cosmograph) (1.1.1)
Requirement already satisfied: platformdirs>=2 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from black>=19.10b0->datamodel-code-generator->ju>=0.1.31->cosmograph) (4.9.4)
Requirement already satisfied: pytokens~=0.4.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from black>=19.10b0->datamodel-code-generator->ju>=0.1.31->cosmograph) (0.4.1)
Requirement already satisfied: boltons>=19.3.0 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from glom->ju>=0.1.31->cosmograph) (25.0.0)
Requirement already satisfied: attrs in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from glom->ju>=0.1.31->cosmograph) (26.1.0)
Requirement already satisfied: face>=20.1.1 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from glom->ju>=0.1.31->cosmograph) (26.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from pandas->cosmograph) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->cosmograph) (1.17.0)
Requirement already satisfied: idna<4,>=2.5 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from requests->ju>=0.1.31->cosmograph) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from requests->ju>=0.1.31->cosmograph) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /home/szabolcs/miniconda3/lib/python3.13/site-packages (from requests->ju>=0.1.31->cosmograph) (2026.6.17)
Note: you may need to restart the kernel to use updated packages.

### Import libraries

In [2]:
import pandas as pd
from cosmograph import cosmo
import ipywidgets as widgets_ipy
from IPython.display import display
from cosmograph import cosmo
import duckdb

### Define cluster representant

In [15]:
CLUSTER_REP="MGYP008633949747"

## 1. Load data
Choose one of the options below

### Option A: Read files using remote FTP

In [70]:
base_url = f"https://ftp.ebi.ac.uk/pub/databases/metagenomics/gsoc_ssn/networks/{CLUSTER_REP}/"

nodes_url = f"{base_url}{CLUSTER_REP}_nodes.parquet"
edges_url = f"{base_url}{CLUSTER_REP}_edges.parquet"

nodes_df = duckdb.sql(f"SELECT * FROM '{nodes_url}'").df()
edges_df = duckdb.sql(f"SELECT * FROM '{edges_url}'").df()

display(nodes_df.head())
display(edges_df.head())

                 id                                              biome
0  MGYP002855862099  root:Host-associated:Mammals:Digestive system:...
1  MGYP002673540755  root:Host-associated:Human:Digestive system:La...
2  MGYP002853144258  root:Host-associated:Mammals:Digestive system:...
3  MGYP002860676619  root:Host-associated:Mammals:Digestive system:...
4  MGYP002627048376  root:Host-associated:Mammals:Digestive system:...

             source            target  sequence_identity
0  MGYP002656457721  MGYP002774926903               98.8
1  MGYP002774926903  MGYP008339877134               98.6
2  MGYP000822534626  MGYP002774926903               98.0
3  MGYP002774926903  MGYP008603557989               98.2
4  MGYP002774926903  MGYP004472909437               98.4

### Option B: Read files locally

In [9]:
nodes_df = pd.read_parquet("MGYP000134696410_nodes.parquet")
edges_df = pd.read_parquet("MGYP000134696410_edges.parquet")

# Quick view of data structure
display(nodes_df.head(5))
display(edges_df.head(5))

                 id                                              biome
0  MGYP000102271628  root:Host-associated:Human:Digestive system:La...
1  MGYP000606320263        root:Host-associated:Human:Digestive system
2  MGYP001470561486  root:Host-associated:Human:Digestive system:La...
3  MGYP007403529906  root:Host-associated:Human:Digestive system:Hi...
4  MGYP009635841147  root:Host-associated:Human:Digestive system:La...

             source            target  sequence_identity
0  MGYP004547913711  MGYP008685658098               99.6
1  MGYP000699390189  MGYP004547913711              100.0
2  MGYP002703219698  MGYP004547913711              100.0
3  MGYP004547913711  MGYP009013785984              100.0
4  MGYP004547913711  MGYP005970380175              100.0

## 2. Create Cosmograph blueprint

Function to set the cluster representant's size and shape different from the other points.

In [74]:
def set_cluster_rep_style(kwargs):
    # Make sure 'points' exist in the kwargs
    if "points" in kwargs and kwargs["points"] is not None:
        points_df = kwargs["points"]
        
        # Add the size and shape column to the temporary copy
        points_df['size'] = 5.0
        points_df.loc[points_df['id'] == CLUSTER_REP, 'node'] = 75.0
        
        # Tell the widget to use this new temporary column
        kwargs["point_size_by"] = "size"
        
    return kwargs

We create a reusable template, determining the style.
All configuration parameters can be found here [here](https://cosmograph.app/docs-widget/configuration/).

In [123]:
graph_style = cosmo(
    point_id_by="id",
    link_source_by="source",
    link_target_by="target",
    ingress=set_cluster_rep_style,
    
    point_color_by="biome",
    #TODO: figure out coloring strategy here
    #figure out what is issue with size 
    point_size_strategy="direct",
    point_label_by="id",
    fit_view_on_init=False,
    select_point_on_click=True,
    select_point_on_label_click=True,
    reset_selection_on_empty_canvas_click=True,
    point_greyout_opacity=0.2, 
    link_greyout_opacity=0.2,
    render_hovered_point_ring=True,
    enable_drag=True,
    show_labels_for=[CLUSTER_REP],
    disable_point_size_legend=True,
)
#TODO: set the params here

# Calling the widget object
This renders the graph locally using your GPU.

In [124]:
graph = graph_style(points=nodes_df, links=edges_df)
graph